document.addEventListener("DOMContentLoaded", main, false); // Wait for DOM elements all loaded

function main() {

    // Call the function 'randomFood()' so it can do its thingy-ma-jigger...

    randomFood();

}

function randomFood() {

    var out = document.getElementById("p1");    // Grab page element to output to

    // Create the obligatory array filled with goodies in our digital pantry

    var favoriteFoods = ['pizza', 'ice cream', 'tacos', 'lasagne', 'egg roll', 'ham and beans'];

    // Create a variable to hold the Math.floor'd number generated by Math.random()

    var todaysMenuItem = 0;

    // Generate a random number, multiply by number of elements in array, 'floor' it, and 
    // assign to 'todaysMenu'

    todaysMenuItem = Math.floor(Math.random() * favoriteFoods.length);

    // Send the food item to the HTML page's output area (p1).  Place 'todaysMenu' variable 
    // inside of the brackets of 'favoriteFoods'.  It will grab the food name in that element.

    out.innerHTML="Today's menu is " + favoriteFoods[todaysMenuItem];
    

}
